import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignInButton, SignOutButton,useUser } from "@clerk/nextjs";

import { RouterOutputs, api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";

dayjs.extend(relativeTime);

const CreatePostWizard = () =>{
  const { user } = useUser();
  console.log(user?.id)
  if(!user) return null;
  return(
    <div className="flex gap-4 w-full">
      <Image 
        src={user.profileImageUrl} 
        alt="Profile Image" 
        className="w-14 h-14 rounded-full" 
        width={56}
        height={56}
      />
      <input placeholder="Type some emojis!" className="bg-transparent outline-none grow"/>
    </div>
  )
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number]

const PostView = (props:  PostWithUser) => {
  const {post, author} = props;
  return(
    <div key={post.id} className="p-4 gap-4 border-b border-slate-400 flex">
     <Image 
        src={author.profilePicture} 
        className="w-14 h-14 rounded-full"
        alt={`@${author.username}'s profile picture`}
        width={56}
        height={56}
      />
     <div className="flex flex-col">
        <div className="flex font-bold text-slate-300 gap-1">
          <span>@{author.username}</span>
          <span className="font-thin">• {dayjs(post.createdAt).fromNow()}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  );
}


const Home: NextPage = () => {
  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();
  
  if (isLoading) return <div>Loading...</div>
  if (!data) return <div>No Posts Yet</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex justify-center">
      <div className="w-full md:max-w-2xl border-x border-slate-400">
        <div className="border-b border-slate-400 p-4 flex">
          {!user.isSignedIn && <div className="flex justify-center"><SignInButton /></div>}
          {user.isSignedIn && <CreatePostWizard />}
        </div>
        <div className="flex-col">
          {data?.map((fullPost) => (
            <PostView {...fullPost} key={fullPost.post.id}/>
          ))}
        </div>
      </div>
      </main>
    </>
  );
};

export default Home;
